########################################################################
#                     Rust Toolchain Configuration                     #
#                                                                      #
# This file governs the Rust toolchain used to build and operate the   #
# project.                                                             #
########################################################################

[toolchain]
channel = "1.56.0"
# channel = "nightly"
profile = "default"
components = [
	"clippy",
	"rustfmt",
]
